### ISSUE TITLE
Unable to access cryptsy_api gem

### ISSUE THREAD

**Issue by JsonSam** [nbarthel/cryptsy-api#12]
Unable to access cryptsy_api gem

2.1.0 :005 > cryptsy = Cryptsy::API::Client.new(api_key, api_secret)
 => #<Cryptsy::API::Client:0x000000039411e8 @key="62f3f575d5b8f260b684717576258cec24aaf7f2", @secret="ac32cc7876a64a69753276d098d2a68016a066c4ca7e4571bc8c4e5bba9c782339aeeaf4444ae7f0", @private_caller=nil> 
2.1.0 :006 > cryptsy.getinfo
JSON::ParserError: 757: unexpected token at '<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>400 - Bad Request</title>
 </head>
 <body>
  <h1>400 - Bad Request</h1>
 <script type="text/javascript">
//<![CDATA[
(function() {
var _analytics_scr = document.createElement('script');
_analytics_scr.type = 'text/javascript'; _analytics_scr.async = true; _analytics_scr.src = '/_Incapsula_Resource?SWJIYLWA=2977d8d74f63d7f8fedbea018b7a1d05&ns=2';
var _analytics_elem = document.getElementsByTagName('script')[0]; _analytics_elem.parentNode.insertBefore(_analytics_scr, _analytics_elem);
})();
// ]]>
</script></body>
</html>

**Comment by nbarthel** [comment]
The error handling in the gem needs work.  I have seen 502s and various issues related to their infrastructure that we don't catch in the gem as well as we could.

I just tried your test  case and had no problem, but my guess is it returned a 400 because of something they were doing on the server.

I'll add some error handling code as time permits, or if someone has time, please submit a pull request for handling HTTP error codes more gracefully.
